# 1. Installation and Array *Basics*

<div dir="rtl" style="text-align: right;">

NumPy کتابخانه‌ی اصلی برای محاسبات علمی در Python است. شیء مرکزی در کتابخانه‌ی NumPy، آرایه‌ی NumPy است. آرایه‌ی NumPy یک شیء آرایه‌ی چندبعدی با عملکرد بالا است که به طور خاص برای انجام عملیات ریاضی، جبر خطی، و محاسبات احتمالات طراحی شده است. استفاده از آرایه‌ی NumPy معمولاً بسیار سریع‌تر است و به کد کمتری نسبت به استفاده از لیست‌های Python نیاز دارد. بخش بزرگی از کتابخانه‌ی NumPy از کد C تشکیل شده که API مربوط به Python به عنوان یک wrapper دور این توابع C عمل می‌کند. این یکی از دلایلی است که NumPy بسیار سریع است.

بیشتر کتابخانه‌های محبوب Machine Learning، Deep Learning، و Data Science در زیرساخت خود از NumPy استفاده می‌کنند:

- Scikit-learn
- Matplotlib
- Pandas

موارد استفاده‌ی مختلف و عملیات‌هایی که می‌توان به راحتی با NumPy انجام داد عبارتند از:

- ضرب داخلی (Dot product/inner product)
- ضرب ماتریسی (Matrix multiplication)
- ضرب المان به المان ماتریس (Element wise matrix product)
- حل دستگاه معادلات خطی (Solving linear systems)
- محاسبه‌ی معکوس ماتریس (Inverse)
- محاسبه‌ی دترمینان (Determinant)
- انتخاب اعداد تصادفی (مثلاً توزیع Gaussian یا Uniform)
- کار با تصاویری که به صورت آرایه نمایش داده می‌شوند

</div>

# 2. Installation and Array Basics

In [50]:
! pip install numpy
# ! conda install numpy

In [51]:
import numpy as np

In [52]:
np.__version__

'2.0.2'

<p dir="rtl">

- در این کد، یک آرایه‌ی NumPy به نام `a` تعریف شده که شامل عناصر `[1, 2, 3, 4, 5]` است.
- `a.shape` : شکل آرایه را نشان می‌دهد که `(5,)` است، یعنی آرایه یک‌بُعدی با ۵ عنصر دارد.
- `a.dtype` : نوع داده‌ی عناصر آرایه را نشان می‌دهد که `int32` است (عدد صحیح ۳۲ بیتی).
- `a.ndim` : تعداد بُعدهای آرایه را مشخص می‌کند. این آرایه یک‌بُعدی است (`1`).
- `a.size` : تعداد کل عناصر آرایه را می‌دهد که برابر با `5` است.
- `a.itemsize` : اندازه‌ی هر عنصر آرایه (بر حسب بایت) را نشان می‌دهد که در اینجا `4` بایت است.

</p>


In [53]:
a = np.array([1,2,3,4,5])
a # [1 2 3 4 5]
a.shape # shape of the array: (5,)
a.dtype # type of the elements: int32
a.ndim # number of dimensions: 1
a.size # total number of elements: 5
a.itemsize # the size in bytes of each element: 4

8

In [54]:
a.itemsize

8

## Essential methods

In [55]:
a = np.array([1,2,3])
# access and change elements
print(a[0]) # 1
a[0] = 5
print(a[0]) # [5 2 3]

# elementwise math operations
b = a * np.array([2,0,2])
print(b) # [10  0  6]

print(a.mean()) # 10

1
5
[10  0  6]
3.3333333333333335


# 3. Array vs List

<p dir="rtl">

- یک لیست `l` و یک آرایه‌ی `a` با مقادیر `[1, 2, 3]` ساخته شده‌اند.
- چاپ `l` و `a` نشان می‌دهد که ظاهر داده‌ها مشابه است، اما آرایه‌ی NumPy ساختار متفاوتی دارد.
- افزودن عنصر جدید:
  - می‌توان به راحتی به لیست `l` مقدار `4` را اضافه کرد.
  - ولی آرایه‌ی NumPy (`a`) اندازه‌ی ثابتی دارد و `append` مستقیم باعث خطا می‌شود.
- برای افزودن آیتم به آرایه، آرایه‌ی جدیدی ساخته می‌شود:
  - `l2 = l + [5]` یک لیست جدید `[1, 2, 3, 4, 5]` می‌سازد.
  - `a2 = a + np.array([4])` عملیات broadcasting انجام می‌دهد و `4` را به هر عنصر `a` اضافه می‌کند، نتیجه `[5, 6, 7]` می‌شود.
- جمع برداری واقعی:
  - `a3 = a + np.array([4, 4, 4])`، که جمع عنصر به عنصر را انجام می‌دهد و نتیجه `[5, 6, 7]` است.
  - اگر اندازه‌ی آرایه‌ها متفاوت باشد، خطا ایجاد می‌شود.
- ضرب:
  - `2 * l` لیست را تکرار می‌کند و نتیجه `[1, 2, 3, 4, 1, 2, 3, 4]` است.
  - `2 * a` هر عنصر آرایه را در ۲ ضرب می‌کند و نتیجه `[2, 4, 6]` است.
- تغییر هر عنصر:
  - با استفاده از حلقه یا list comprehension می‌توان مربع هر عنصر لیست را محاسبه کرد (`[1, 4, 9, 16]`).
  - برای آرایه، `a**2` مستقیماً مربع هر عنصر را حساب می‌کند (`[1, 4, 9]`).
- توابع بر روی آرایه:
  - توابعی مانند `np.sqrt(a)`, `np.exp(a)`, `np.tanh(a)` به صورت عنصر به عنصر عمل می‌کنند.
  - `np.sqrt(a)` جذر عناصر را محاسبه می‌کند.
  - `np.log(a)` لگاریتم طبیعی عناصر را محاسبه می‌کند.

</p>


In [56]:
l = [1,2,3]
a = np.array([1,2,3])# create an array from a list
print(l) # [1, 2, 3]
print(a) # [1 2 3]

# adding new item
l.append(4)
# a.append(4) #error: size of array is fixed

# there are ways to add items, but this essentially creates new arrays
l2 = l + [5]
print(l2) # [1, 2, 3, 4, 5]

a2 = a + np.array([4])
print(a2) # this is called broadcasting, adds 4 to each element
# -> [5 6 7]

# vector addidion (this is technically correct compared to broadcasting)
a3 = a + np.array([4,4,4])
print(a3) # [5 6 7]

# a3 = a + np.array([4,5]) # error, can't add vectors of different sizes

# multiplication
l2 = 2 * l # list l repeated 2 times, same a l+l
print(l2)
# -> [1, 2, 3, 4, 1, 2, 3, 4]

a3 = 2 * a # multiplication for each element
print(a3)
# -> [2 4 6]

# modify each item in the list
l2 = []
for i in l:
    l2.append(i**2)
print(l2) # [1, 4, 9, 16]

# or list comprehension
l2 = [i**2 for i in l]
print(l2) # [1, 4, 9, 16]

a2 = a**2 # -> squares each element!
print(a2) # [1 4 9]

# Note: function applied to array usually operates element wise
a2 = np.sqrt(a) # np.exp(a), np.tanh(a)
print(a2) # [1. 1.41421356 1.73205081]
a2 = np.log(a)
print(a2) # [0. 0.69314718 1.09861229]



[1, 2, 3]
[1 2 3]
[1, 2, 3, 4, 5]
[5 6 7]
[5 6 7]
[1, 2, 3, 4, 1, 2, 3, 4]
[2 4 6]
[1, 4, 9, 16]
[1, 4, 9, 16]
[1 4 9]
[1.         1.41421356 1.73205081]
[0.         0.69314718 1.09861229]


# 4. Dot Product

<p dir="rtl">

- دو آرایه‌ی `a` و `b` به ترتیب با مقادیر `[1, 2]` و `[3, 4]` ساخته شده‌اند.
- هدف محاسبه‌ی ضرب داخلی (dot product) بین این دو آرایه است.
- روش دستی (مخصوص لیست‌ها):
  - از یک حلقه‌ی `for` استفاده شده و حاصل‌ضرب هر جفت عنصر محاسبه و با هم جمع شده‌اند.
  - نتیجه برابر با `11` شده است.
- روش آسان‌تر با NumPy:
  - تابع `np.dot(a, b)` به طور مستقیم ضرب داخلی را محاسبه می‌کند و خروجی `11` است.
- محاسبه‌ی گام به گام:
  - ابتدا ضرب عنصر به عنصر انجام شده (`c = a * b`) که نتیجه `[3, 8]` است.
  - سپس مجموع این آرایه محاسبه شده (`d = np.sum(c)`) که مقدار `11` را به دست می‌دهد.
- روش‌های دیگر:
  - از متدهای نمونه (instance methods) نیز می‌توان استفاده کرد:
    - `a.dot(b)`
    - `(a*b).sum()`
- در نسخه‌های جدیدتر پایتون و NumPy:
  - می‌توان از عملگر `@` برای محاسبه‌ی ضرب داخلی استفاده کرد: `a @ b` که نتیجه همان `11` خواهد بود.

</p>


In [57]:
a = np.array([1,2])
b = np.array([3,4])

# sum of the products of the corresponding entries
# multiply each corresponding elements and then take the sum

# cumbersome way for lists
dot = 0
for i in range(len(a)):
    dot += a[i] * b[i]
print(dot) # 11

# easy with numpy :)
dot = np.dot(a,b)
print(dot) # 11

# step by step manually
c = a * b
print(c) # [3 8]
d = np.sum(c)
print(d) # 11

# most of these functions are also instance methods
dot = a.dot(b)
print(dot) # 11
dot = (a*b).sum()
print(dot) # 11

# in newer versions
dot = a @ b
print(dot) # 11

11
11
[3 8]
11
11
11
11


# 5. Speed Test array vs list

<p dir="rtl">

- در این کد، هدف مقایسه‌ی سرعت محاسبه‌ی ضرب داخلی (`dot product`) بین لیست‌های معمولی پایتون و آرایه‌های NumPy است.
- ابتدا دو آرایه‌ی تصادفی `a` و `b` با ۱۰۰۰ عنصر ساخته شده و معادل لیستی آن‌ها (`A` و `B`) نیز ایجاد شده است.
- دو تابع تعریف شده است:
  - `dot1()` : محاسبه‌ی ضرب داخلی با استفاده از حلقه‌ی `for` روی لیست‌های معمولی.
  - `dot2()` : محاسبه‌ی ضرب داخلی با استفاده از تابع بهینه‌ی `np.dot` روی آرایه‌های NumPy.
- برای هر روش، زمان اجرا اندازه‌گیری شده است:
  - `timer()` از ماژول `timeit` برای ثبت زمان شروع و پایان استفاده شده است.
  - هر تابع `T=1000` بار اجرا شده تا زمان محاسبه قابل توجه باشد.
- نتایج:
  - زمان اجرای `dot1()` (لیست‌ها) بسیار بیشتر از `dot2()` (آرایه‌ها) است.
  - نسبت سرعت محاسبه شده نشان می‌دهد که آرایه‌های NumPy حدود ۱۷۲ برابر سریع‌تر هستند.

</p>


In [58]:
from timeit import default_timer as timer

a = np.random.randn(1000)
b = np.random.randn(1000)

A = list(a)
B = list(b)

T = 1000

def dot1():
    dot = 0
    for i in range(len(A)):
        dot += A[i]*B[i]
    return dot

def dot2():
    return np.dot(a,b)

start = timer()
for t in range(T):
    dot1()
end = timer()
t1 = end-start

start = timer()
for t in range(T):
    dot2()
end = timer()
t2 = end-start

print('Time with lists:', t1) # -> 0.19371
print('Time with array:', t2) # -> 0.00112
print('Ratio', t1/t2)         # -> 172.332 times faster

Time with lists: 0.3397058709999783
Time with array: 0.002729538999574288
Ratio 124.45540109628784


# 6. Multidimensional (nd) arrays

<p dir="rtl">

- آرایه‌ی `a` به صورت ماتریس `2×2` تعریف شده است:
- `a.shape` : شکل آرایه را نمایش می‌دهد که `(2, 2)` است.
- دسترسی به عناصر:
- `a[0]` : سطر اول را می‌دهد `[1 2]`.
- `a[0][0]` یا `a[0,0]` : عنصر در سطر ۰ و ستون ۰، یعنی `1` را می‌دهد.
- برش (slicing):
- `a[:,0]` : تمام سطرها در ستون اول را می‌دهد `[1 3]`.
- `a[0,:]` : تمام ستون‌ها در سطر اول را می‌دهد `[1 2]`.
- ترانهاده (Transpose):
- `a.T` ماتریس `a` را ترانهاده می‌کند (ردیف‌ها و ستون‌ها را جابه‌جا می‌کند).
- ضرب ماتریسی:
- `c = a.dot(b)` ضرب ماتریسی `a` و `b` را محاسبه می‌کند.
- توجه: ابعاد داخلی باید با هم مطابقت داشته باشند.
- اگر لازم باشد، می‌توان `b` را ترانهاده کرد (`b.T`) تا ابعاد مناسب شوند.
- ضرب عنصری:
- `d = a * b` ضرب عنصر به عنصر بین `a` و `b` انجام می‌دهد.
- دترمینان (Determinant):
- `np.linalg.det(a)` دترمینان ماتریس `a` را محاسبه می‌کند.
- معکوس ماتریس:
- `np.linalg.inv(a)` معکوس ماتریس `a` را محاسبه می‌کند (اگر ماتریس معکوس‌پذیر باشد).
- کار با قطر اصلی (Diagonal):
- `np.diag(a)` عناصر قطر اصلی ماتریس `a` را به صورت آرایه باز می‌گرداند `[1, 4]`.
- `np.diag([1, 4])` یک ماتریس قطری با عناصر `1` و `4` می‌سازد:
  ```
  [[1 0]
   [0 4]]
  ```

</p>


In [59]:
# (matrix class exists but not recommended to use)
a = np.array([[1,2], [3,4]])
print(a)
#[[1 2]
#[3 4]]

print(a.shape) # (2, 2)

# Access elements
# row first, then columns
print(a[0]) # [1 2]
print(a[0][1]) # 1
# or
print(a[0,0]) # 1

# slicing
print(a[:,0]) # all rows in col 0:    [1 3]
print(a[0,:]) # all columns in row 0: [1 2]

# transpose
a.T

# matrix multiplication
b = np.array([[3, 4], [5,6]])
c = a.dot(b)
c

d = a * b # elementwise multiplication

# inner dimensions must match!
b = np.array([[1,2], [4,5]]) # Changed b to have shape (2, 2)
c = a.dot(b.T) # Now b.T has shape (2, 2) which is compatible with a

# determinant
c = np.linalg.det(a)
c

# inverse
c = np.linalg.inv(a)

# diag
c = np.diag(a)
print(c) # [1 4]

# diag on a vector returns diagonal matrix (overloaded function)
c = np.diag([1,4])
print(c)
# [[1 0]
#  [0 4]]

[[1 2]
 [3 4]]
(2, 2)
[1 2]
2
1
[1 3]
[1 2]
[1 4]
[[1 0]
 [0 4]]


# 7. Indexing/Slicing/Boolean Indexing

<p dir="rtl">

- در این کد با عملیات **برش (Slicing)** و **ایندکس‌گذاری (Indexing)** روی آرایه‌های چندبُعدی NumPy آشنا می‌شویم.
- آرایه‌ی `a` یک ماتریس `3×4` تعریف شده است:
- ایندکس‌گذاری عدد صحیح (Integer Array Indexing):
- `a[0,1]` عنصر سطر ۰ و ستون ۱ را برمی‌گرداند که مقدار آن `2` است.
- برش (Slicing):
- `a[0,:]` تمام ستون‌های سطر اول (`[1 2 3 4]`) را انتخاب می‌کند.
- `a[:,0]` تمام سطرهای ستون اول (`[1 5 9]`) را انتخاب می‌کند.
- `a[0:2,1:3]` یک زیرماتریس از سطرهای ۰ و ۱ و ستون‌های ۱ و ۲ را برمی‌گرداند:
  ```
  [[2 3]
   [6 7]]
  ```
- ایندکس‌گذاری از انتها:
- `a[-1,-1]` عنصر آخرین سطر و آخرین ستون را برمی‌گرداند که مقدار `12` است.

</p>


# Indexing and Slicing

<p dir="rtl">

- آرایه‌ی `a` یک ماتریس `3×4` است که به شکل زیر تعریف شده:
- **ایندکس عدد صحیح (Integer Indexing)**:
- `a[0,1]` عنصر سطر اول و ستون دوم (عدد `2`) را بازمی‌گرداند.
- **برش (Slicing)**:
- `a[0,:]` تمام ستون‌های سطر اول را انتخاب می‌کند: `[1 2 3 4]`.
- `a[:,0]` تمام سطرهای ستون اول را انتخاب می‌کند: `[1 5 9]`.
- `a[0:2,1:3]` زیرماتریسی شامل سطرهای ۰ و ۱ و ستون‌های ۱ و ۲ را برمی‌گرداند:
  ```
  [[2 3]
   [6 7]]
  ```
- **ایندکس‌گذاری از انتها**:
- `a[-1,-1]` عنصر آخرین سطر و آخرین ستون را انتخاب می‌کند که مقدار آن `12` است.

</p>


In [60]:
# Slicing: Similar to Python lists, numpy arrays can be sliced.
# Since arrays may be multidimensional, you must specify a slice for each
# dimension of the array:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]

# Integer array indexing
b = a[0,1]
print(b) # 2

# Slicing
row0 = a[0,:]
print(row0) # [1 2 3 4]

col0 = a[:, 0]
print(col0) # [1 5 9]

slice_a = a[0:2,1:3]
print(slice_a)
# [[2 3]
#  [6 7]]

# indexing starting from the end: -1, -2 etc...
last = a[-1,-1]
print(last) # 12

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
2
[1 2 3 4]
[1 5 9]
[[2 3]
 [6 7]]
12


# Boolean indexing

In [61]:
# Boolean indexing:
a = np.array([[1,2], [3, 4], [5, 6]])
print(a)
# [[1 2]
#  [3 4]
#  [5 6]]

# same shape with True or False for the condition
bool_idx = a > 2
print(bool_idx)
#  [[False False]
#   [ True  True]
#   [ True  True]]

# note: this will be a rank 1 array!
print(a[bool_idx]) # [3 4 5 6]

# We can do all of the above in a single concise statement:
print(a[a > 2]) # [3 4 5 6]

# np.where(): same size with modified values
b = np.where(a>2, a, -1)
print(b)
# [[-1 -1]
#  [ 3  4]
#  [ 5  6]]

# fancy indexing: access multiple indices at once
a = np.array([10,19,30,41,50,61])

b = a[[1,3,5]]
print(b) # [19 41 61]

# compute indices where condition is True
even = np.argwhere(a%2==0).flatten()
print(even) # [0 2 4]

a_even = a[even]
print(a_even) # [10 30 50]

[[1 2]
 [3 4]
 [5 6]]
[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]
[3 4 5 6]
[[-1 -1]
 [ 3  4]
 [ 5  6]]
[19 41 61]
[0 2 4]
[10 30 50]


# 8. Reshaping

In [62]:
a = np.arange(1, 7)
print(a) # [1 2 3 4 5 6]

b = a.reshape((2, 3)) # error if shape cannot be used
print(b)
# [[1 2 3]
#  [4 5 6]]

c = a.reshape((3, 2)) # 3 rows, 2 columns
print(c)
# [[1 2]
#  [3 4]
#  [5 6]]

# newaxis is used to create a new axis in the data
# needed when model require the data to be shaped in a certain manner
print(a.shape) # (6,)

d = a[np.newaxis, :]
print(d) # [[1 2 3 4 5 6]]
print(d.shape) # (1, 6)

e = a[:, np.newaxis]
print(e)
# [[1]
#  [2]
#  [3]
#  [4]
#  [5]
#  [6]]
print(e.shape) # (6, 1)


[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]
(6,)
[[1 2 3 4 5 6]]
(1, 6)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
(6, 1)


# 9. Concatenation

<p dir="rtl">

- هدف این بخش، ترکیب آرایه‌های NumPy در ابعاد مختلف است.

- **تبدیل به آرایه‌ی یک‌بعدی**:
  - `np.concatenate((a, b), axis=None)` آرایه‌های `a` و `b` را در یک آرایه‌ی ۱-بعدی ترکیب می‌کند.
  - خروجی: `[1 2 3 4 5 6]`

- **افزودن یک سطر جدید**:
  - `np.concatenate((a, b), axis=0)` آرایه‌ی `b` را به عنوان یک سطر جدید به `a` اضافه می‌کند.
  - خروجی:
    ```
    [[1 2]
     [3 4]
     [5 6]]
    ```

- **افزودن یک ستون جدید**:
  - برای افزودن ستون، ابتدا باید `b` را ترانهاده (`b.T`) کنیم و سپس با `a` در امتداد محور ۱ (ستون‌ها) ترکیب کنیم.
  - خروجی:
    ```
    [[1 2 5]
     [3 4 6]]
    ```

- **ترکیب افقی با `hstack`**:
  - `np.hstack((a,b))` آرایه‌ها را به صورت افقی (ستونی) در کنار هم قرار می‌دهد.
  - برای آرایه‌های ۱-بعدی:
    - `[1 2 3 4 5 6 7 8]`
  - برای آرایه‌های ۲-بعدی:
    ```
    [[1 2 5 6]
     [3 4 7 8]]
    ```

- **ترکیب عمودی با `vstack`**:
  - `np.vstack((a,b))` آرایه‌ها را به صورت عمودی (سطر به سطر) روی هم قرار می‌دهد.
  - برای آرایه‌های ۱-بعدی:
    ```
    [[1 2 3 4]
     [5 6 7 8]]
    ```
  - برای آرایه‌های ۲-بعدی:
    ```
    [[1 2]
     [3 4]
     [5 6]
     [7 8]]
    ```

</p>


In [63]:
a = np.array([[1, 2], [3, 4]])

b = np.array([[5, 6]])

# combine into 1d
c = np.concatenate((a, b), axis=None)
print(c) # [1 2 3 4 5 6]

# add new row
d = np.concatenate((a, b), axis=0)
print(d)
# [[1 2]
#  [3 4]
#  [5 6]]

# add new column: note that we have to transpose b!
e = np.concatenate((a, b.T), axis=1)
print(e)
# [[1 2 5]
#  [3 4 6]]

# hstack: Stack arrays in sequence horizontally (column wise). needs a tuple
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
c = np.hstack((a,b))
print(c) # [1 2 3 4 5 6 7 8]

a = np.array([[1,2], [3,4]])
b = np.array([[5,6], [7,8]])
c = np.hstack((a,b))
print(c)
# [[1 2 5 6]
#  [3 4 7 8]]

# vstack: Stack arrays in sequence vertically (row wise). needs a tuple
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
c = np.vstack((a,b))
print(c)
# [[1 2 3 4]
#  [5 6 7 8]]

a = np.array([[1,2], [3,4]])
b = np.array([[5,6], [7,8]])
c = np.vstack((a,b))
print(c)
# [[1 2]
#  [3 4]
#  [5 6]
#  [7 8]]

[1 2 3 4 5 6]
[[1 2]
 [3 4]
 [5 6]]
[[1 2 5]
 [3 4 6]]
[1 2 3 4 5 6 7 8]
[[1 2 5 6]
 [3 4 7 8]]
[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


# 10. Broadcasting

In [64]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
y = np.array([1, 0, 1])
z = x + y  # Add v to each row of x using broadcasting
print(z)
# [[ 2  2  4]
#  [ 5  5  7]
#  [ 8  8 10]
#  [11 11 13]]

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


<div dir="rtl" style="text-align: right;">

Broadcasting یک مکانیزم قدرتمند است که به numpy اجازه می‌دهد با آرایه‌هایی با شکل‌های متفاوت هنگام انجام عملیات‌های ریاضی کار کند. اغلب اوقات یک آرایه‌ی کوچکتر و یک آرایه‌ی بزرگتر داریم و می‌خواهیم از آرایه‌ی کوچکتر چندین بار برای انجام عملیاتی روی آرایه‌ی بزرگتر استفاده کنیم.

</div>


# 11. Functions and Axis

<p dir="rtl">

- آرایه‌ی `a` یک ماتریس `2×7` به شکل زیر است:
[[ 7 8 9 10 11 12 13] [17 18 19 20 21 22 23]]


### ✅ مجموع (Sum)
- `a.sum()` یا `a.sum(axis=None)` : مجموع تمام عناصر → `210`
- `a.sum(axis=0)` : جمع هر ستون (در امتداد سطرها) → `[24 26 28 30 32 34 36]`
- `a.sum(axis=1)` : جمع هر سطر (در امتداد ستون‌ها) → `[70 140]`

### ✅ میانگین (Mean)
- `a.mean()` یا `a.mean(axis=None)` : میانگین کلی عناصر → `15.0`
- `a.mean(axis=0)` : میانگین هر ستون → `[12. 13. 14. 15. 16. 17. 18.]`
- `a.mean(axis=1)` : میانگین هر سطر → `[10. 20.]`

### ℹ️ نکته:
توابع آماری مانند `sum`, `mean`, `std`, `var`, `min`, `max` می‌توانند بر اساس محور دلخواه محاسبه شوند:
- `axis=0`: اعمال روی ستون‌ها (سطر به سطر)
- `axis=1`: اعمال روی سطرها (ستون به ستون)
- `axis=None`: اعمال روی کل آرایه

</p>


In [65]:
a = np.array([[7,8,9,10,11,12,13], [17,18,19,20,21,22,23]])

print(a.sum())          # default=None-> 210
print(a.sum(axis=None)) # overall sum -> 210

print(a.sum(axis=0)) # along the rows -> 1 sum entry for each column
# -> [24 26 28 30 32 34 36]

print(a.sum(axis=1)) # along the columns -> 1 sum entry for each row
# -> [ 70 140]


print(a.mean())          # default=None-> 15.0
print(a.mean(axis=None)) # overall mean -> 15.0

print(a.mean(axis=0)) # along the rows -> 1 mean entry for each column
# -> [12. 13. 14. 15. 16. 17. 18.]

print(a.mean(axis=1)) # along the columns -> 1 mean entry for each row
# -> [10. 20.]

# some more: std, var, min, max

210
210
[24 26 28 30 32 34 36]
[ 70 140]
15.0
15.0
[12. 13. 14. 15. 16. 17. 18.]
[10. 20.]


# 12. Datatypes

<p dir="rtl">

### نوع داده‌ها (Data Types) در NumPy

- هنگام ساخت آرایه‌های NumPy، نوع داده (dtype) عناصر به صورت خودکار یا دستی تعیین می‌شود.

---

- `np.array([1, 2])`  
  - چون مقادیر صحیح هستند، NumPy نوع `int32` را به صورت پیش‌فرض انتخاب می‌کند.
  - خروجی: `int32`

- `np.array([1.0, 2.0])`  
  - چون مقادیر اعشاری هستند، NumPy نوع `float64` را انتخاب می‌کند (دقت ۶۴ بیتی).
  - خروجی: `float64`

---

### 🔧 تعیین دستی نوع داده (dtype)

- `np.array([1, 2], dtype=np.int64)`  
  - نوع داده به صورت صریح `int64` مشخص شده (عدد صحیح با دقت ۶۴ بیت / ۸ بایت).
  - خروجی: `int64`

- `np.array([1, 2], dtype=np.float32)`  
  - نوع داده به صورت `float32` مشخص شده (عدد اعشاری با دقت ۳۲ بیت / ۴ بایت).
  - خروجی: `float32`

---

✅ با تعیین دقیق نوع داده، می‌توان بین **دقت عددی** و **مصرف حافظه** توازن ایجاد کرد، مخصوصاً در داده‌های بزرگ یا کاربردهای پردازشی خاص.

</p>


In [66]:
# Let numpy choose the datatype
x = np.array([1, 2])
print(x.dtype) # int32

# Let numpy choose the datatype
x = np.array([1.0, 2.0])
print(x.dtype) # float64

# Force a particular datatype, how many bits (how precise)
x = np.array([1, 2], dtype=np.int64) # 8 bytes
print(x.dtype) # int64

x = np.array([1, 2], dtype=np.float32) # 4 bytes
print(x.dtype) # float32

int64
float64
int64
float32


# 13. Copying

<p dir="rtl">

### 🔁 تفاوت بین **کپی ارجاعی** و **کپی واقعی** در NumPy

- وقتی یک آرایه را مستقیماً به متغیر دیگری نسبت می‌دهیم (`b = a`)، در واقع فقط **ارجاع (reference)** آن آرایه کپی می‌شود، نه محتوای واقعی آن.

```python
a = np.array([1,2,3])
b = a           # فقط ارجاع کپی می‌شود
b[0] = 42       # تغییر در b باعث تغییر در a نیز می‌شود
print(a)        # خروجی: [42  2  3]
```

- برای ایجاد یک **کپی واقعی از داده‌ها** (یعنی آرایه‌ی جدید در حافظه)، باید از متد `.copy()` استفاده کنیم:

```python
a = np.array([1,2,3])
b = a.copy()    # کپی واقعی از داده‌ها
b[0] = 42       # تغییر در b اثری روی a ندارد
print(a)        # خروجی: [1  2  3]
```

✅ استفاده از `.copy()` در مواقعی که می‌خواهید داده‌ی اصلی دست‌نخورده باقی بماند **ضروری** است.

</p>

# 14. Generating arrays

<p dir="rtl">

### ساخت آرایه‌ها با مقادیر خاص در NumPy

- NumPy امکانات زیادی برای ساخت آرایه‌های اولیه با مقادیر از پیش تعیین‌شده فراهم می‌کند.

---

- `np.zeros((2,3))`  
  - آرایه‌ای `2×3` با مقدار صفر ایجاد می‌کند.
  - خروجی:
    ```
    [[0. 0. 0.]
     [0. 0. 0.]]
    ```

- `np.ones((2,3))`  
  - آرایه‌ای `2×3` با مقدار یک ایجاد می‌کند.
  - خروجی:
    ```
    [[1. 1. 1.]
     [1. 1. 1.]]
    ```

- `np.full((3,3), 5.0)`  
  - آرایه‌ای `3×3` با مقدار دلخواه `5.0` ایجاد می‌کند.
  - خروجی:
    ```
    [[5. 5. 5.]
     [5. 5. 5.]
     [5. 5. 5.]]
    ```

- `np.eye(3)`  
  - ماتریس همانی (واحد) `3×3` تولید می‌کند.
  - خروجی:
    ```
    [[1. 0. 0.]
     [0. 1. 0.]
     [0. 0. 1.]]
    ```

- `np.arange(10)`  
  - آرایه‌ای از اعداد صحیح پشت‌سر‌هم از `0` تا `9` ایجاد می‌کند.
  - خروجی:
    ```
    [0 1 2 3 4 5 6 7 8 9]
    ```

- `np.linspace(0, 10, 5)`  
  - آرایه‌ای شامل ۵ مقدار **با فاصله‌ی برابر** بین `0` تا `10` ایجاد می‌کند.
  - خروجی:
    ```
    [ 0.   2.5  5.   7.5 10. ]
    ```

</p>


In [67]:
# zeros
a = np.zeros((2,3)) # size as tuple
# [[0. 0. 0.]
#  [0. 0. 0.]]

# ones
b = np.ones((2,3))
# [[1. 1. 1.]
#  [1. 1. 1.]]

# specific value
c = np.full((3,3),5.0)
# [[5. 5. 5.]
#  [5. 5. 5.]
#  [5. 5. 5.]]

# identity
d = np.eye(3) #3x3
# [[1. 0. 0.]
#  [0. 1. 0.]
#  [0. 0. 1.]]

# arange
e = np.arange(10)
# [0 1 2 3 4 5 6 7 8 9]

# linspace
f = np.linspace(0, 10, 5)
# [ 0.  2.5  5.  7.5  10. ]

# 15. Random numbers

<p dir="rtl">

### تولید مقادیر تصادفی در NumPy

NumPy امکانات متنوعی برای تولید داده‌های تصادفی فراهم می‌کند — از توزیع‌های یکنواخت و نرمال گرفته تا انتخاب تصادفی از آرایه‌ها.

---

#### 🎲 تولید اعداد تصادفی پیوسته

- `np.random.random((3,2))`  
  - تولید آرایه‌ای `3×2` با مقادیر تصادفی در بازه‌ی `[0, 1)` با **توزیع یکنواخت (Uniform)**.
  - نمونه خروجی:
    ```
    [[0.06 0.10]
     [0.83 0.54]
     [0.94 0.19]]
    ```

- `np.random.randn(3,2)`  
  - تولید آرایه‌ای `3×2` با مقادیر تصادفی دارای **توزیع نرمال استاندارد (میانگین ۰، واریانس ۱)**.
  - نکته: در `randn` هر بعد به‌صورت جداگانه به عنوان آرگومان وارد می‌شود، نه به‌صورت `tuple`.

---

#### 📊 بررسی آماری

- `np.random.randn(10000)`  
  - ایجاد ۱۰,۰۰۰ عدد تصادفی با توزیع نرمال، سپس محاسبه‌ی میانگین، واریانس و انحراف معیار آن‌ها.
  - میانگین تقریباً `0` و انحراف معیار تقریباً `1` خواهد بود.

- `d.mean()`  
  - میانگین کل عناصر آرایه‌ی `d` را محاسبه می‌کند.

---

#### 🔢 تولید اعداد صحیح تصادفی

- `np.random.randint(3,10, size=(3,3))`  
  - تولید آرایه‌ای `3×3` از اعداد صحیح تصادفی در بازه‌ی `[3, 10)`، یعنی از ۳ تا ۹.

---

#### 🎯 انتخاب تصادفی از مجموعه‌ای از اعداد

- `np.random.choice(7, size=10)`  
  - انتخاب ۱۰ عدد تصادفی از بین `[0, 1, 2, 3, 4, 5, 6]` (یعنی ۷ مقدار ممکن).

- `np.random.choice([1,2,3,4], size=8)`  
  - انتخاب ۸ عدد تصادفی از آرایه‌ی `[1, 2, 3, 4]` — مقدارها می‌توانند تکراری باشند.

---

✅ این توابع برای شبیه‌سازی آماری، تولید داده‌ی تمرینی، و تست مدل‌ها بسیار پرکاربرد هستند.

</p>


In [68]:
a = np.random.random((3,2)) # uniform 0-1 distribution
# [[0.06121857 0.10180167]
#  [0.83321726 0.54906613]
#  [0.94170273 0.19447411]]

b = np.random.randn(3,2) # normal/Gaussian distribution, mean 0 and unit variance
# no tuple as shape here! each dimension one argument
# [[ 0.56759123 -0.65068333]
#  [ 0.83445762 -0.36436185]
#  [ 1.27150812 -0.32906051]]

c = np.random.randn(10000)
print(c.mean(), c.var(), c.std())
# -0.0014 0.9933 0.9966

d = np.random.randn(10, 3)
print(d.mean()) # mean of whole array: -0.1076827228882305

# random integer, low,high,size; high is exclusive
e = np.random.randint(3,10,size=(3,3)) # if we only pass one parameter, then from 0-x
print(e)
# [[6 8 4]
#  [3 6 3]
#  [4 7 8]]

# with integer is between 0 up to integer exclusive
f = np.random.choice(7, size=10)
# [2 0 4 5 1 3 4 0 0 6]

# with an array it draws random values from this array
g = np.random.choice([1,2,3,4], size=8)
# [4 2 1 3 4 1 4 1]

-0.003121542549126532 0.9824815955034428 0.9912020961960496
-0.006312262412775293
[[8 9 6]
 [6 6 6]
 [6 9 6]]


# 16. Linear Algebra (Eigenvalues / Solving Linear Systems)

## Eigenvalues


<p dir="rtl">

### مقادیر و بردارهای ویژه (Eigenvalues & Eigenvectors) در NumPy

- با استفاده از تابع `np.linalg.eig(a)` می‌توان **مقادیر ویژه** و **بردارهای ویژه** یک ماتریس را محاسبه کرد.

---

#### 🧮 تعریف ماتریس:
```python
a = np.array([[1,2],
              [3,4]])
```

---

#### 🧠 محاسبه:

- `eigenvalues, eigenvectors = np.linalg.eig(a)`  
  - `eigenvalues`: آرایه‌ای شامل مقادیر ویژه.
  - `eigenvectors`: ماتریسی که ستون‌های آن بردارهای ویژه‌ی مربوط به مقادیر ویژه هستند.

  نمونه خروجی:
  ```python
  eigenvalues  = [-0.37228132  5.37228132]
  eigenvectors = [[-0.82456484 -0.41597356]
                  [ 0.56576746 -0.90937671]]
  ```

- `eigenvectors[:,0]`  
  - ستون اول از ماتریس بردارهای ویژه → مربوط به مقدار ویژه‌ی اول.

---

#### ✅ بررسی رابطه‌ی اصلی:

- رابطه‌ی پایه‌ای:
  \[
  A \cdot v = \lambda \cdot v
  \]
  که در آن \( v \) بردار ویژه و \( \lambda \) مقدار ویژه است.

- با کد:
  ```python
  d = eigenvectors[:,0] * eigenvalues[0]
  e = a @ eigenvectors[:, 0]
  ```

- در ظاهر `d` و `e` برابرند، اما مقایسه‌ی مستقیم با `==` ممکن است به خاطر خطاهای عددی (floating-point) درست عمل نکند:
  ```python
  d == e # ممکن است False باشد
  ```

- روش صحیح برای مقایسه‌ی عددی در NumPy:
  ```python
  np.allclose(d, e) # خروجی: True
  ```

---

✅ اگر ماتریس شما **متقارن** باشد (Symmetric)، پیشنهاد می‌شود از تابع **`np.linalg.eigh`** استفاده کنید که سریع‌تر و دقیق‌تر است.

</p>


In [69]:
a = np.array([[1,2], [3,4]])
eigenvalues, eigenvectors = np.linalg.eig(a)
# Note: use eigh if your matrix is symmetric (faster)

print(eigenvalues)
 #  [-0.37228132  5.37228132]

print(eigenvectors) # column vectors
# [[-0.82456484 -0.41597356]
#  [ 0.56576746 -0.90937671]]

print(eigenvectors[:,0]) # column 0 corresponding to eigenvalue[0]
# [-0.82456484  0.56576746]

# verify: e-vec * e-val = A * e-vec
d = eigenvectors[:,0] * eigenvalues[0]
e = a @ eigenvectors[:, 0]

print(d, e) # [ 0.30697009 -0.21062466] [ 0.30697009 -0.21062466]
# looks the same, but:
print(d == e) # [ True False] -> numerical issues

# correct way to compare matrix
print(np.allclose(d,e)) # True

[-0.37228132  5.37228132]
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]
[-0.82456484  0.56576746]
[ 0.30697009 -0.21062466] [ 0.30697009 -0.21062466]
[ True False]
True


## Solving Linear Systems


<p dir="rtl">

### 🔎 حل دستگاه معادلات خطی با NumPy

در این مثال، یک دستگاه دو معادله و دو مجهول داریم:

\[
\begin{cases}
x_1 + x_2 = 2200 \\
1.5x_1 + 4x_2 = 5050
\end{cases}
\]

---

### ✅ نمایش ماتریسی:
این دستگاه را می‌توان به‌صورت \( Ax = b \) نوشت:

- ماتریس ضرایب (A):
```python
A = np.array([[1, 1],
              [1.5, 4]])
```

- بردار نتایج (b):
```python
b = np.array([2200, 5050])
```

---

### ❌ روش نادرست (غیربهینه): استفاده از معکوس

- `np.linalg.inv(A).dot(b)`  
  - ابتدا معکوس ماتریس محاسبه شده و سپس در بردار ضرب می‌شود.
  - گرچه جواب درست می‌دهد (`[1500. 700.]`)، اما:
    - **کندتر**
    - **کم‌دقت‌تر**
    - **پایدار نبودن عددی (numerical instability)**

---

### ✅ روش توصیه‌شده: استفاده از `np.linalg.solve`

- `np.linalg.solve(A, b)`  
  - سریع‌تر و دقیق‌تر.
  - مستقیماً دستگاه \( Ax = b \) را حل می‌کند.

- خروجی:  
  ```
  x = [1500.  700.]
  ```

یعنی:
- \( x_1 = 1500 \)
- \( x_2 = 700 \)

</p>

In [70]:
#     x1 + x2   = 2200
# 1.5 x1 + 4 x2 = 5050
# -> 2 equations and 2 unknowns
A = np.array([[1, 1], [1.5, 4]])
b = np.array([2200,5050])

# Ax = b <=> x = A-1 b

# But: inverse is slow and less accurate
x = np.linalg.inv(A).dot(b) # not recommended
print(x) # [1500.  700.]

# instead use:
x = np.linalg.solve(A,b) # good
print(x) # [1500.  700.]

[1500.  700.]
[1500.  700.]


# 17. Loading CSV files


<p dir="rtl">

### 📄 خواندن داده از فایل CSV با NumPy

NumPy توابع مختلفی برای بارگذاری داده‌های عددی از فایل‌ها فراهم می‌کند. در اینجا دو روش رایج بررسی شده‌اند:

---

### 1️⃣ `np.loadtxt()`

- تابعی ساده و سریع برای خواندن فایل‌های متنی با مقادیر عددی.
- مناسب وقتی که داده‌ها کامل و بدون مقادیر گمشده (missing values) باشند.

```python
data = np.loadtxt('my_file.csv', delimiter=",", dtype=np.float32)
```

- `delimiter=","` → جداکننده‌ی ستون‌ها.
- `dtype=np.float32` → نوع داده‌ی عددی.
- می‌توان از `skiprows=1` برای نادیده گرفتن سطر عنوان (header) استفاده کرد.
- نمونه خروجی:
  ```python
  print(data.shape, data.dtype)
  ```

---

### 2️⃣ `np.genfromtxt()`

- انعطاف‌پذیرتر از `loadtxt`، مخصوصاً در مواجهه با **داده‌های ناقص یا مقادیر گمشده**.

```python
data = np.genfromtxt('my_file.csv', delimiter=",", dtype=np.float32)
```

- پارامترهای اضافی:
  - `skip_header=1` : رد کردن ردیف عنوان.
  - `missing_values="---"` : مقدار مشخصی را به عنوان داده‌ی گمشده شناسایی کند.
  - `filling_values=0.0` : مقدار جایگزین برای سلول‌های گمشده.

- مناسب برای داده‌هایی که ممکن است بعضی سلول‌ها پر نشده باشند یا با فرمت متفاوت ذخیره شده‌اند.

---

✅ انتخاب بین `loadtxt` و `genfromtxt` بستگی به ساختار فایل دارد:  
- **ساده و تمیز؟** → `loadtxt`  
- **با داده‌ی ناقص؟** → `genfromtxt`

</p>

In [71]:
# 1) load with np.loadtxt()
# skiprows=1, ...
data = np.loadtxt('my_file.csv', delimiter=",", dtype=np.float32, skiprows=1) # skip the first row (header)
print(data.shape, data.dtype)

# 2) load with np.genfromtxt()
# similar but slightly more configuration parameters
# skip_header=0, missing_values="---", filling_values=0.0, ...
data = np.genfromtxt('my_file.csv', delimiter=",", dtype=np.float32, skip_header=1) #skip the first row (header)
print(data.shape)

(5, 3) float32
(5, 3)
